### PR TITLE
Add a Spanish translation

### PR DESCRIPTION
**Pull request by gaetanlhf**
Thanks to Isabel Albar, ZimWiki can now have a Spanish translation. :)
Do you have any thoughts on this PR?

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Spanish translations are neat. Thanks!
A Spanish (native) speaking friend of mine suggested "Resultados de la búsqueda para" (note the additional 'para') would be a better translation for "Search results for". The rest looks fine.

**Comment by gaetanlhf** [comment]
The translations that I offer you come from a Spanish speaker, but in fact she did not translate literally the English "for"... 
She probably didn't think it was necessary, but since you asked for it, I will add it. :)

**Comment by gaetanlhf** [comment]
It's done. :)

**Comment by JojiiOfficial** [comment]
Thanks!

**Pull request merged**
