### PR TITLE
Redesign of the web user interface and fix of some issues

### PR DESCRIPTION
**Pull request by gaetanlhf**
### Changes:
- Switch to Bootstrap 5
- Switch to Fork Awesome
- All libraries are now served locally
- A little redesign for the web interface
- The main JavaScript script is now jQuery-free
- Changing the appearance of the search results page

### Fixes:
- Fixed scrolling to object if url ends with '#<id>'
- Iframes are now displayed fully and responsively
- Do not search if the search field is empty or contains only spaces

### New:
- The title displayed in the browser is the title of the iframe

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Is this still WIP? I've noticed there are still commits towards this PR.

**Comment by gaetanlhf** [comment]
It's not WIP anymore.
I took the opportunity to modify some elements instead of redoing a PR that would have the same purpose...
You can now review this PR in all tranquility, the next new additions will come in a separate PR.

**Comment by gaetanlhf** [comment]
Would you like me to take care of making new screenshots or will you take care of that after reviewing this PR? 🤔

**Comment by JojiiOfficial** [comment]
The new design looks good! Although there is one thing I have to comment on.

In my opinion the new title bar is too big (in height). I tried to make the initial design in a way that it looks almost exactly the same as if you were actually visiting the page. 
image
On phone the top bar takes up even more space:


Probably removing the title is fine for mobile. The best solution for mobile (and PC too) is probably a FAB (floating action button) or at least removing some padding from the top-bar, but this is just a suggestion.

Big thanks for this huge PR!

**Comment by gaetanlhf** [comment]
Hi Jojii,
Thanks for reviewing this PR.
Indeed, it is true that the header bar is rather huge, and the space between it and the iframe too.
I didn't find it too problematic, but yes, space saving is interesting.
I'll work on that. :)

**Comment by gaetanlhf** [comment]
What do you think of this last commit?
Screenshot 2021-06-19 at 18-38-47 Oxygène
Screenshot 2021-06-19 at 18-39-10 Oxygène

**Comment by JojiiOfficial** [comment]
This is much better. Thanks!

**Pull request merged**
