### PR TITLE
Add spinner if server takes too long to respond + iframe

### PR DESCRIPTION
**Pull request by gaetanlhf**
This new PR adds the display of a spinner if the server takes more than four seconds to respond to a POST.
Also, when loading an iframe, a spinner is displayed in an elegant way.

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Looks nice! Unfortunately on my machine the spinner gets displayed instantly, even if the site takes only half a second to load. This makes it a bit weird to click through a wiki. I used an incognito tab (latest chromium version) to prevent the cache from manipulating the intended js code.

**Comment by gaetanlhf** [comment]
There are two cases where the spinner is displayed:
- Case 1: during a POST, if it lasts more than four seconds

https://user-images.githubusercontent.com/81755261/129581646-1391472a-8ba1-40d8-9939-08a1ac1dbc13.mp4

- Case 2: when loading an iframe

https://user-images.githubusercontent.com/81755261/129581898-2767c3a9-1892-494b-a86e-7fd9dba87381.mp4

What case are you talking about?
I tested in Mozilla Firefox and in Ungoogled Chromium and everything seems to work perfectly.
If it's case 2 that bothers you, it's actually not an error in the JavaScript code, but just one of my ideas to make the navigation more pleasant (and avoid seeing the images appearing one by one).
But maybe in reality it is not pleasant?
If it's not the case, I can change that!

**Comment by JojiiOfficial** [comment]
I like both spinners but in my opinion case 2 should have a timeout until it gets fired. On my machine most pages nearly load instantly so seeing the spinner if a page loads in ~10-100ms is too intrusive in my opinion. Showing it after maybe 500ms of loading a new site without response is much better in my opinion.

**Comment by gaetanlhf** [comment]
Yes indeed, it can be a bit intrusive and disturb the navigation...
The iframe spinner is now displayed only if it takes more than 100ms to be ready (which will rarely be the case except on a slow server). :)

**Comment by gaetanlhf** [comment]
I have forgotten something...
If you wish, the German translation will have to be updated (new entry: "Loading...").

**Comment by gaetanlhf** [comment]
Hey Jojii,
Do you have any thoughts on these latest changes?

**Comment by JojiiOfficial** [comment]
I think 100ms is still not enough. I just tested it and now sometimes if the page is already loaded, for a very short amount the loading screen flashes up and instantly hides again. I tested it with 300ms and this worked fine. What do you think about changing it to ~300ms?

**Comment by gaetanlhf** [comment]
I agree, it's not bad to put 300ms!
And thanks for the update of the German translation.
If this is okay for you, I think it's time to merge. :)

**Pull request merged**
