### PR TITLE
Caching of search results for smoother navigation

### PR DESCRIPTION
**Pull request by gaetanlhf**
This new PR features the ability to cache search results for a period of time, for a smoother navigation.
This can be configured from the `config.toml` configuration file.
What are your thoughts on this? :)

### CODE REVIEW

**Comment by JojiiOfficial** [comment]
Sounds good. Does this cache have a configurable limit? I'm currently unavailable to do a proper review, I'll review it when I have more time

**Comment by gaetanlhf** [comment]
This cache is not limited to the amount of memory used, yet to the lifetime of each element within it.
For a simpler explanation than I could do, here is a link to the documentation: https://github.com/zgoat/zcache#faq
If you don't like it, don't worry, I will revise my copy. :)

**Comment by gaetanlhf** [comment]
Hey, did you have time to check this PR? :)

**Comment by JojiiOfficial** [comment]
Yep looks good. Thanks for the ping.

**Pull request merged**
